trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    useGlobalJson: true

- task: PowerShell@2
  displayName: 'Build Samples'
  inputs:
    targetType: filePath
    filePath: ./build.ps1
    failOnStderr: true

